/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetPosition.java
 *
 * Created on 04.12.2011, 13:27:59
 */
package graphpresentation;

import graphnet.GraphPetriPlace;

/**
 *
 * @author Оля
 */
public class SetPosition extends javax.swing.JFrame {

    /**
     * Creates new form SetPosition
     */
    public SetPosition(PetriNetsPanel panel) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.panel = panel;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPositionPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        markLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        markTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setTitle("Параметри вершини");
        setResizable(false);

        setPositionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Основні параметри"));

        nameLabel.setText("Ім'я");

        markLabel.setText("Маркування");

        nameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        markTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout setPositionPanelLayout = new javax.swing.GroupLayout(setPositionPanel);
        setPositionPanel.setLayout(setPositionPanelLayout);
        setPositionPanelLayout.setHorizontalGroup(
            setPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPositionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(markLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(markTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addContainerGap())
        );
        setPositionPanelLayout.setVerticalGroup(
            setPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPositionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markLabel)
                    .addComponent(markTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        okButton.setText("Ок");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Відмінити");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setPositionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setPositionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            setPName();
            setPMark();
            choosenPetriP = null;
            panel.repaint();
            this.setVisible(false);
        } catch (NumberFormatException e) {
            markTextField.setText("");
            markTextField.setToolTipText("Введіть ціле число");
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        choosenPetriP = null;
        panel.repaint();
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void setPName() {
        choosenPetriP.getPetriPlace().setName(nameTextField.getText());
    }

    private void setPMark() {
        choosenPetriP.getPetriPlace().setMark(Integer.valueOf(markTextField.getText()));
    }

    private void setChoosen(GraphElement e) {
        choosenPetriP = (GraphPetriPlace) e;
    }

    private void getPName() {
        nameTextField.setText(choosenPetriP.getPetriPlace().getName());
    }

    private void getPMark() {
        markTextField.setText(Integer.toString(choosenPetriP.getPetriPlace().getMark()));
    }

    public void setInfo(GraphElement e) {
        setChoosen(e);
        getPName();
        getPMark();
    }
    private PetriNetsPanel panel;
    private GraphPetriPlace choosenPetriP;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel markLabel;
    private javax.swing.JTextField markTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel setPositionPanel;
    // End of variables declaration//GEN-END:variables
}
