/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetTransition.java
 *
 * Created on 02.12.2011, 18:21:37
 */
package graphpresentation;

import graphnet.GraphPetriTransition;

/**
 *
 * @author User
 */
public class SetTransition extends javax.swing.JFrame {

    /** Creates new form SetTransition */
    public SetTransition(PetriNetsPanel panel) {
        initComponents();
          this.setLocationRelativeTo(null);
         this.panel=panel;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseParametersPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        timeDelayPanel = new javax.swing.JPanel();
        parametrLabel = new javax.swing.JLabel();
        parametrTextField = new javax.swing.JTextField();
        destributionLabel = new javax.swing.JLabel();
        destributionComboBox = new javax.swing.JComboBox();
        paramDeviationLabel = new javax.swing.JLabel();
        paramDeviationTextField = new javax.swing.JTextField();
        priorityPanel = new javax.swing.JPanel();
        priorityLabel = new javax.swing.JLabel();
        prioritySpinner = new javax.swing.JSpinner();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        probabilityLabel = new javax.swing.JLabel();
        probabilityTextField = new javax.swing.JTextField();

        setTitle("Параметри переходу");
        setResizable(false);

        baseParametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Базові параметри"));

        nameLabel.setText("Ім'я");

        nameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout baseParametersPanelLayout = new javax.swing.GroupLayout(baseParametersPanel);
        baseParametersPanel.setLayout(baseParametersPanelLayout);
        baseParametersPanelLayout.setHorizontalGroup(
            baseParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseParametersPanelLayout.createSequentialGroup()
                .addComponent(nameLabel)
                .addGap(53, 53, 53)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        baseParametersPanelLayout.setVerticalGroup(
            baseParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nameLabel)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        timeDelayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Часова затримка"));

        parametrLabel.setText("Середнє значення затримки");

        parametrTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        parametrTextField.setText("0.0");

        destributionLabel.setText("Розподіл часу затримки");

        destributionComboBox.setEditable(true);
        destributionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "exp", "unif", "norm" }));
        destributionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destributionComboBoxActionPerformed(evt);
            }
        });

        paramDeviationLabel.setText("Середнє квадр. відхилення");

        paramDeviationTextField.setEditable(false);
        paramDeviationTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paramDeviationTextField.setText("0.0");

        javax.swing.GroupLayout timeDelayPanelLayout = new javax.swing.GroupLayout(timeDelayPanel);
        timeDelayPanel.setLayout(timeDelayPanelLayout);
        timeDelayPanelLayout.setHorizontalGroup(
            timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeDelayPanelLayout.createSequentialGroup()
                .addGroup(timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timeDelayPanelLayout.createSequentialGroup()
                        .addComponent(parametrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(parametrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(timeDelayPanelLayout.createSequentialGroup()
                        .addComponent(destributionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(destributionComboBox, 0, 99, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(timeDelayPanelLayout.createSequentialGroup()
                    .addComponent(paramDeviationLabel)
                    .addContainerGap(106, Short.MAX_VALUE)))
            .addGroup(timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timeDelayPanelLayout.createSequentialGroup()
                    .addContainerGap(156, Short.MAX_VALUE)
                    .addComponent(paramDeviationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        timeDelayPanelLayout.setVerticalGroup(
            timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeDelayPanelLayout.createSequentialGroup()
                .addGroup(timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parametrLabel)
                    .addComponent(parametrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destributionLabel)
                    .addComponent(destributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(timeDelayPanelLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(paramDeviationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
            .addGroup(timeDelayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(timeDelayPanelLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(paramDeviationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        priorityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Пріоритет переходу"));

        priorityLabel.setText("Значення пріоритету");

        prioritySpinner.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout priorityPanelLayout = new javax.swing.GroupLayout(priorityPanel);
        priorityPanel.setLayout(priorityPanelLayout);
        priorityPanelLayout.setHorizontalGroup(
            priorityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priorityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(prioritySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        priorityPanelLayout.setVerticalGroup(
            priorityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priorityPanelLayout.createSequentialGroup()
                .addGroup(priorityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityLabel)
                    .addComponent(prioritySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Відмінити");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ймовірність спрацьовування", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        probabilityLabel.setText("Значення ймовірності");

        probabilityTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        probabilityTextField.setText("1.0");
        probabilityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probabilityTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(probabilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(probabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(probabilityLabel)
                    .addComponent(probabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timeDelayPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baseParametersPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priorityPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baseParametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeDelayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priorityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.getAccessibleContext().setAccessibleName("Ймовірність");

        getAccessibleContext().setAccessibleName(""); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
     try{
        setTName();
        setTimeDelay();
        setPriority();
        choosenPetriT=null;
        this.setVisible(false);
        panel.repaint();
     }
      catch (NumberFormatException e){        
       } 
    }//GEN-LAST:event_okButtonActionPerformed
 
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
        panel.repaint();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void destributionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destributionComboBoxActionPerformed
     
        if ((destributionComboBox.getSelectedIndex()==2)||(destributionComboBox.getSelectedIndex()==3)) 
        paramDeviationTextField.setEditable(true);
     
       // TODO add your handling code here:
    }//GEN-LAST:event_destributionComboBoxActionPerformed

    private void probabilityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probabilityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_probabilityTextFieldActionPerformed

     /**
      * @param args the command line arguments
      */

private void setTName(){
    choosenPetriT.getPetriTransition().setName(nameTextField.getText());
}
    private void setTimeDelay() {
  
        choosenPetriT.getPetriTransition().setParametr(Double.valueOf(parametrTextField.getText()));
        choosenPetriT.getPetriTransition().setProbability(Double.valueOf(probabilityTextField.getText()));
        if (destributionComboBox.getSelectedIndex()==0) 
           choosenPetriT.getPetriTransition().setDistribution(null, Double.valueOf(parametrTextField.getText()));
       if (destributionComboBox.getSelectedIndex()==1) 
       choosenPetriT.getPetriTransition().setDistribution("exp", Double.valueOf(parametrTextField.getText()));
        
       if (destributionComboBox.getSelectedIndex()==2) 
           { 
               choosenPetriT.getPetriTransition().setDistribution("unif", Double.valueOf(parametrTextField.getText()));
               paramDeviationTextField.setEditable(true);
               choosenPetriT.getPetriTransition().setParamDeviation(Double.valueOf(paramDeviationTextField.getText()));
           }
       if (destributionComboBox.getSelectedIndex()==3) 
            { 
                choosenPetriT.getPetriTransition().setDistribution("norm", Double.valueOf(parametrTextField.getText()));
                paramDeviationTextField.setEditable(true);
                choosenPetriT.getPetriTransition().setParamDeviation(Double.valueOf(paramDeviationTextField.getText()));
            }
       
      
     }

     private void setPriority() {
        choosenPetriT.getPetriTransition().setPriority((Integer) prioritySpinner.getModel().getValue());
     }

     public void getPriority() {
         prioritySpinner.setValue(choosenPetriT.getPetriTransition().getPriority());
             }
     private void getTName(){
          nameTextField.setText(choosenPetriT.getPetriTransition().getName());
     }
     private void getTimeDelay(){
          parametrTextField.setText(Double.toString(choosenPetriT.getPetriTransition().getParametr()));
           probabilityTextField.setText(Double.toString(choosenPetriT.getPetriTransition().getProbability()));
     }
     private void setChoosen(GraphElement e){
         choosenPetriT=(GraphPetriTransition)e;
     }  
     public void setInfo(GraphElement e){
         setChoosen(e);
         getTName();
         getTimeDelay();
         getPriority();
     }
     private PetriNetsPanel panel;
     private GraphPetriTransition choosenPetriT;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baseParametersPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox destributionComboBox;
    private javax.swing.JLabel destributionLabel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel paramDeviationLabel;
    private javax.swing.JTextField paramDeviationTextField;
    private javax.swing.JLabel parametrLabel;
    private javax.swing.JTextField parametrTextField;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JPanel priorityPanel;
    private javax.swing.JSpinner prioritySpinner;
    private javax.swing.JLabel probabilityLabel;
    private javax.swing.JTextField probabilityTextField;
    private javax.swing.JPanel timeDelayPanel;
    // End of variables declaration//GEN-END:variables
}
